id: PD2856120
initial_creation_type: input
source_metadata:
  Title: Vajrasattvaniṣpādana Sūtra
  Editor: Luo Hong & Toru Tomabechi
  Publisher: China Tibetology Publishing House
  Place of Publication: Beijing
  Year: '-'
  Vajrasattvaniṣpādana Sūtra:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:15:59.065484'
last_modified_at: '2022-03-08T17:15:59.065492'
